## Project Description
Find factors that related to 'accident severity'

### 1. Importing the required libraries

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns #visualization
import matplotlib.pyplot as plt #visualization
%matplotlib inline
sns.set(color_codes=True)

### 2. Loading the data in to the data frame

In [4]:
df = pd.read_csv("Data-Collisions.csv")
df.head(10)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N
5,1,-122.387598,47.690575,6,320840,322340,E919477,Matched,Intersection,36974.0,...,Dry,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
6,1,-122.338485,47.618534,7,83300,83300,3282542,Matched,Intersection,29510.0,...,Wet,Daylight,NaN,8344002.0,NaN,10,Entering at angle,0,0,N
7,2,-122.320780,47.614076,9,330897,332397,EA30304,Matched,Intersection,29745.0,...,Dry,Daylight,NaN,NaN,NaN,5,Vehicle Strikes Pedalcyclist,6855,0,N
8,1,-122.335930,47.611904,10,63400,63400,2071243,Matched,Block,NaN,...,Dry,Daylight,NaN,6166014.0,NaN,32,One parked--one moving,0,0,N
9,2,-122.384700,47.528475,12,58600,58600,2072105,Matched,Intersection,34679.0,...,Dry,Daylight,NaN,6079001.0,NaN,10,Entering at angle,0,0,N

### 3. Checking the types of data

In [6]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: object

### 4. Dropping irrelevant columns

In [25]:
# df = df.drop(['SEVERITYCODE', 'X', 'Y', 'INCKEY', 'COLDETKEY', 'INTKEY', 'REPORTNO', 'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'SDOT_COLCODE', 'SDOT_COLDESC', 'SDOTCOLNUM', 'ST_COLCODE', 'ST_COLDESC'], axis=1)
# df = df.drop(['OBJECTID', 'STATUS', 'LOCATION', 'PERSONCOUNT', 'PEDCYLCOUNT', 'PEDCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE'], axis=1)
# df = df.drop(['ADDRTYPE', 'INCDATE', 'INCDTTM', 'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'], axis=1)
df.head(10)

,SEVERITYCODE.1,SEVERITYDESC,COLLISIONTYPE,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SPEEDING
0,2,Injury Collision,Angles,NaN,N,Overcast,Wet,Daylight,NaN,NaN
1,1,Property Damage Only Collision,Sideswipe,NaN,0,Raining,Wet,Dark - Street Lights On,NaN,NaN
2,1,Property Damage Only Collision,Parked Car,NaN,0,Overcast,Dry,Daylight,NaN,NaN
3,1,Property Damage Only Collision,Other,NaN,N,Clear,Dry,Daylight,NaN,NaN
4,2,Injury Collision,Angles,NaN,0,Raining,Wet,Daylight,NaN,NaN
5,1,Property Damage Only Collision,Angles,NaN,N,Clear,Dry,Daylight,NaN,NaN
6,1,Property Damage Only Collision,Angles,NaN,0,Raining,Wet,Daylight,NaN,NaN
7,2,Injury Collision,Cycles,NaN,N,Clear,Dry,Daylight,NaN,NaN
8,1,Property Damage Only Collision,Parked Car,NaN,0,Clear,Dry,Daylight,NaN,NaN
9,2,Injury Collision,Angles,NaN,0,Clear,Dry,Daylight,NaN,NaN

In [17]:
df.count()

OBJECTID          194673
STATUS            194673
ADDRTYPE          192747
LOCATION          191996
SEVERITYCODE.1    194673
SEVERITYDESC      194673
COLLISIONTYPE     189769
PERSONCOUNT       194673
PEDCOUNT          194673
PEDCYLCOUNT       194673
VEHCOUNT          194673
INCDATE           194673
INCDTTM           194673
JUNCTIONTYPE      188344
INATTENTIONIND     29805
UNDERINFL         189789
WEATHER           189592
ROADCOND          189661
LIGHTCOND         189503
PEDROWNOTGRNT       4667
SPEEDING            9333
SEGLANEKEY        194673
CROSSWALKKEY      194673
HITPARKEDCAR      194673
dtype: int64

In [14]:
df.shape

(194673, 24)

In [16]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 24)

OBJECTID           int64
STATUS            object
ADDRTYPE          object
LOCATION          object
SEVERITYCODE.1     int64
SEVERITYDESC      object
COLLISIONTYPE     object
PERSONCOUNT        int64
PEDCOUNT           int64
PEDCYLCOUNT        int64
VEHCOUNT           int64
INCDATE           object
INCDTTM           object
JUNCTIONTYPE      object
INATTENTIONIND    object
UNDERINFL         object
WEATHER           object
ROADCOND          object
LIGHTCOND         object
PEDROWNOTGRNT     object
SPEEDING          object
SEGLANEKEY         int64
CROSSWALKKEY       int64
HITPARKEDCAR      object
dtype: object